{"name": "skopt_gp_default_cube", "package": "skopt", "strategy": "skopt_gp_default", "traceback": "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/skoptcube.py\", line 61, in skopt_gp_default_cube\n    method='')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/skoptcube.py\", line 51, in skopt_gp_cube_factory\n    result = gp_minimize(func=_objective,  dimensions=bounds, n_calls=n_trials, n_jobs=1, **gp_params)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/skopt/optimizer/gp.py\", line 268, in gp_minimize\n    callback=callback, n_jobs=n_jobs, model_queue_size=model_queue_size)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/skopt/optimizer/base.py\", line 249, in base_minimize\n    \"Expected `n_calls` >= %d, got %d\" % (required_calls, n_calls))\nValueError: Expected `n_calls` >= 10, got 5\n"}