{"n_dim": 34, "n_trials": 340, "objective": "qing_on_cube", "white": "pymoo_unsga3", "black": "ultraopt_forest", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/comparison/eloratings.py\", line 79, in optimizer_game\n    with_count=True)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 43, in ultraopt_forest_cube\n    method='Forest')\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/humpday/optimizers/ultraoptcube.py\", line 31, in ultraopt_cube_factory\n    n_jobs=1, show_progressbar=False, parallel_strategy=\"Serial\" )\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/facade/fmin.py\", line 106, in fmin\n    opt_.tell(config, loss)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 63, in tell\n    self.new_result(job, update_model=update_model)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/base_opt.py\", line 101, in new_result\n    self._new_result(budget, vectors, losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/optimizer/bo/sampling_sort_opt.py\", line 72, in _new_result\n    y_obvs = self.loss_transformer.fit_transform(losses)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 41, in fit_transform\n    y = super(LogScaledLossTransformer, self).fit_transform(y)\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/ultraopt/utils/loss_transformer.py\", line 17, in fit_transform\n    y[y >= ERR_LOSS] = y[y < ERR_LOSS].max() + 0.1\n  File \"/Users/petercotton/virtual-envs/optimizer-elo-ratings/lib/python3.7/site-packages/numpy/core/_methods.py\", line 39, in _amax\n    return umr_maximum(a, axis, None, out, keepdims, initial, where)\nValueError: zero-size array to reduction operation maximum which has no identity\n"], "best_val": [8242614425004.462, null], "best_x": [[0.3632904415899062, 0.23478013146746646, 0.35009428768437567, 0.32036685476043125, 0.28931708456198457, 0.2560033446337634, 0.3300056240606667, 0.2795361724679022, 0.5226743793140389, 0.2610073656774373, 0.3343089554934542, 0.23526155779489233, 0.3387856731417279, 0.6910375751234151, 0.2998549196276451, 0.7452129864768282, 0.5130226023490569, 0.2137427014760066, 0.3496398907274316, 0.29195205197888074, 0.1785924808512086, 0.29297015318615827, 0.2756631417776363, 0.38166639817268977, 0.5769002419374915, 0.4265484497744283, 0.629540084529363, 0.7304940103289034, 0.12667771658540472, 0.3145710907040634, 0.30234739745907846, 0.6216286082327811, 0.2564110163722104, 0.04852566969877459], null], "feval_count": [340, null], "n_trials_instructed": [340, 340], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}